set( EXE_NAME vvenc_scheduler_test )
file( GLOB SRC_FILES CONFIGURE_DEPENDS "*.cpp" )
file( GLOB INC_FILES CONFIGURE_DEPENDS "*.h" )
add_executable( ${EXE_NAME} ${SRC_FILES} ${INC_FILES} )
set_target_properties( ${EXE_NAME} PROPERTIES RELEASE_POSTFIX "${CMAKE_RELEASE_POSTFIX}" )
set_target_properties( ${EXE_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}" )
target_compile_options( ${EXE_NAME} PRIVATE $<$<CXX_COMPILER_ID:GNU>:-Wall -Wno-sign-compare -Wno-unused-result>)
target_include_directories( ${EXE_NAME} PRIVATE ${VVENC_LIB_DIR} )
target_link_libraries( ${EXE_NAME} Threads::Threads vvenc )
set_target_properties( ${EXE_NAME} PROPERTIES FOLDER test )
