#!/usr/bin/env python3
"""
LightGBM training script for CU split prediction models.
Trains 5 binary classifiers (QT, BH, BV, TH, TV) on feature data
generated by the instrumented VVenC encoder.

Usage:
    python train_lightgbm.py \
        --train train.csv \
        --val val.csv \
        --output-dir ./models
"""

import argparse
import os
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split


def train_binary_classifier(X_train, y_train, X_val, y_val, split_name, output_dir):
    """Train a single binary LightGBM classifier for one split type."""
    neg_count = (y_train == 0).sum()
    pos_count = (y_train == 1).sum()
    scale_pos_weight = neg_count / pos_count if pos_count > 0 else 1.0
    print(f"    pos={pos_count} neg={neg_count} scale_pos_weight={scale_pos_weight:.1f}")
    model = lgb.LGBMClassifier(
        objective="binary",
        metric="binary_logloss",
        n_estimators=1000,
        num_leaves=255,
        learning_rate=0.02,
        early_stopping_rounds=50,
        scale_pos_weight=scale_pos_weight,
        min_child_samples=50,
        min_split_gain=0.0,
        reg_alpha=0.0,
        reg_lambda=0.0,
        verbosity=1,
        random_state=42,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric="binary_logloss",
    )

    out_path = os.path.join(output_dir, f"{split_name.lower()}_split_model.txt")
    model.booster_.save_model(out_path)
    print(f"  Saved {out_path}  (best iteration: {model.best_iteration_})")

    return model


def main():
    parser = argparse.ArgumentParser(description="Train LightGBM CU split predictors")
    parser.add_argument("--train", required=True, help="Path to training CSV")
    parser.add_argument("--val", required=True, help="Path to validation CSV")
    parser.add_argument("--output-dir", default="./models", help="Model output directory")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print("Loading training data...")
    df_train = pd.read_csv(args.train)
    df_val = pd.read_csv(args.val)

    # The label column is named 'best_split'
    # Drop frame/position metadata — not available at encode time
    exclude = {"best_split", "poc", "ctu_x", "ctu_y"}
    feature_cols = [c for c in df_train.columns if c not in exclude]

    X_train = df_train[feature_cols]
    y_train = df_train["best_split"]
    X_val = df_val[feature_cols]
    y_val = df_val["best_split"]

    print(f"  Train: {len(X_train)} rows, {len(feature_cols)} features")
    print(f"  Val:   {len(X_val)} rows")

    split_types = ["QT", "BH", "BV", "TH", "TV"]

    for split_name in split_types:
        print(f"\nTraining {split_name} classifier...")
        y_train_bin = (y_train == split_name).astype(int)
        y_val_bin = (y_val == split_name).astype(int)
        train_binary_classifier(
            X_train, y_train_bin,
            X_val, y_val_bin,
            split_name, args.output_dir,
        )

    print(f"\nAll models saved to {args.output_dir}/")
    for name in split_types:
        path = os.path.join(args.output_dir, f"{name.lower()}_split_model.txt")
        size_kb = os.path.getsize(path) / 1024
        print(f"  {name.lower()}_split_model.txt  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
